// Mocks generated by Mockito 5.4.0 from annotations
// in loyalty_program_frontend/test/utils/helpers/loyalty_points_checker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:loyalty_program_frontend/presentation/utils/helpers/loyalty_program_event.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoyaltyProgramEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoyaltyProgramEvent extends _i1.Mock
    implements _i2.LoyaltyProgramEvent {
  @override
  void appOpened() => super.noSuchMethod(
        Invocation.method(
          #appOpened,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void stayedInApp() => super.noSuchMethod(
        Invocation.method(
          #stayedInApp,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void completedLesson() => super.noSuchMethod(
        Invocation.method(
          #completedLesson,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
