name: Flutter Automatic Testing
on: pull_request

jobs:
  run-jest-tests:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.10

      - name: Install all dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Run Test Coverage
        run: flutter test --coverage
      
      - name: Check if coverage is under minimum coverage
        run: ./check_coverage.sh