name: Flutter Automatic Testing
on: pull_request

jobs:
  run-jest-tests:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.10

      - name: Install Lcov
        run: sudo apt-get -y install lcov

      - name: Install zip library
        run:  sudo apt install zip

      - name: Install all dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Run Test Coverage
        run: flutter test --coverage
      
      - name: Check if coverage is under minimum coverage
        run: ./check_coverage.sh

      - name: Generate HTML from coverage
        if: always()
        run:  genhtml coverage/lcov.info -o coverageReport

      - name: convert folder to zip
        if: always()
        run: zip -r ~/coverageReport.zip coverageReport

      - name: Add to artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: UnitTestCoverageReport
          path: ~/coverageReport.zip

      